project_id = "bgrhahojcelswqichcib"

[functions.detect-disease]
verify_jwt = false

[functions.predict-yield]
verify_jwt = false

[functions.irrigation-recommendations]
verify_jwt = false

[functions.ai-assistant]
verify_jwt = false

[functions.ai-contextual-tip]
verify_jwt = false